version: '3.8'

services:
  nvr-frontend:
    container_name: nvr-frontend
    build:
      context: ../nvr_webrtc_frontend
      dockerfile: Dockerfile
    image: slokingdg/nvr_webrtc_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - nvr-backend
    restart: always
    networks:
      nvr-network:
        ipv4_address: 172.20.0.10

  nvr-backend:
    container_name: nvr-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: slokingdg/nvr_webrtc_backend:latest
    environment:
      - PORT=3000
      - JWT_SECRET=4345ee152ce84f7292bf45cd58a6f99e211e67c9e9c4a02c79b6b0175dbe5765
      - DEBUG_MODE=false
      - NVR_USERNAME=tecnologia
      - NVR_PASSWORD=Tecn02026+
    volumes:
      # Mantener la persistencia de SQLite (nodos, usuarios y plantillas) en el volumen del host
      - nvr-db-volume:/app/nvr.db
    restart: always
    networks:
      nvr-network:
        ipv4_address: 172.20.0.11

networks:
  nvr-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  nvr-db-volume:
    driver: local
